---
title: "Lab1"
author: "Eleanore Brugh"
date: "2026-02-22"
output: html_document
---

###lab exercises
```{r}
library(tidyverse)
library(ggplot2)
library(sf)
library(dplyr)
```

```{r}
p.counties <- "C:/R/Data/CBW/County_Boundaries.shp"
p.stations <- "C:/R/Data/CBW/Non-Tidal_Water_Quality_Monitoring_Stations_in_the_Chesapeake_Bay.shp"
```

```{r}
d.counties <- sf::read_sf(p.counties)
d.stations <- sf::read_sf(p.stations)
```

```{r}
glimpse(d.counties)
glimpse(d.stations)
```

```{r}
d.stations %>% sf::st_is_valid()
```

```{r}
d.counties %>% sf::st_is_valid()
```

```{r}
d.counties <- d.counties %>% sf::st_make_valid()
```

#dplyr
```{r}
d.counties %>% dplyr::select(GEOID10, ALAND10) %>% head()
```

```{r}
d.counties %>% dplyr::select(-NAME10) %>% head() 
```

```{r}
d.counties %>% dplyr::select(GEOID10:CLASSFP10) %>% head() 
```

```{r}
d.counties %>% dplyr::select(-(GEOID10:CLASSFP10)) %>% head()
```

```{r}
d.counties %>% dplyr::select(starts_with("C"))
```

#grouping data
```{r}
d.counties %>% group_by(STATEFP10) %>% mutate(stateLandArea = sum(ALAND10))
```

#without geometry
```{r}
d.counties %>% {
  as_tibble(d.counties) %>% dplyr::select(-geometry) %>%
    group_by(STATEFP10) %>%
    summarise(stateLandArea = sum(ALAND10))}
```

#plot (+)
```{r}
d.counties %>% {
  ggplot(., aes(x = as.factor(STATEFP10), y = ALAND10)) +
    geom_boxplot(aes(fill = STATEFP10))}
```

```{r}
d.counties %>% {
  ggplot(., aes(x = ALAND10)) +
    geom_histogram(aes(fill = STATEFP10)) +
    labs(title = "not useful")}
```

##spatial operations
#same CRS
```{r}
d.counties %>% sf::st_crs() == d.stations %>% sf::st_crs()
```

#trimming data
```{r}
del.counties <- d.counties %>% dplyr::filter(STATEFP10 == 10)
```

#spatial intersection
```{r}
del.stations <- sf::st_intersection(d.stations, del.counties)
```

```{r}
glimpse(del.stations)
```
```{r}
plot(del.stations)
```
```{r}

```
```{r}
del.counties %>% st_area()
```






####Task 1
##task1_1
```{r}
task1_1 <- d.counties %>% 
  as_tibble() %>% dplyr::select(-geometry) %>%
  group_by(STATEFP10) %>%
  mutate(totalStateLandArea = sum(ALAND10 + AWATER10),
  (land_percent_total_area = ALAND10 / totalStateLandArea) * 100) 
```

##task1-2
#calculated the water proportion group function not needed
```{r}
prop_calc <- d.counties %>%
  as_tibble() %>% dplyr::select(-geometry) %>%
  mutate(water_proportion = AWATER10 / (ALAND10 + AWATER10))
```

```{r}
glimpse(prop_calc)
```

#find max value and create new table
#need state, county, and water proportion
```{r}
task1_2 <- prop_calc %>%
  group_by(STATEFP10) %>%
  slice_max(water_proportion, n = 1) %>%
  select(STATEFP10, NAME10, water_proportion)
```

```{r}
glimpse(task1_2)
```

##task1-3
#no group just calculation
```{r}
task1_3 <- d.counties %>%
  as_tibble() %>% dplyr::select(-geometry) %>%
  count(STATEFP10, name = "count_perstate")
```

```{r}
glimpse(task1_3)
```







